namespace: "alikins"
name: "ansible_testing_content"
version: "3.1.8"
description: "a collection for testing ansible collections"
authors: ["Galaxy Team", "Adrian Likins"]
license: "GPL-3.0-or-later"
dependencies: []
