namespace: "alikins"
name: "ansible_testing_content"
version: "4.0.3"
description: "a collection for testing ansible collections"
authors: ["Galaxy Team", "Adrian Likins"]
license:
  - "GPL-3.0-or-later"
readme: "README.md"
homepage: "https://github.com/alikins/ansible-testing-content"
tags:
  - collectiontest
dependencies: {}
